### ISSUE TITLE
ESP32-E22_OE3WAS_V2.0.3

### ISSUE THREAD

**Issue by karamo** [DK9BT/esp32-e22-lora-board#3]
neue Version: Fehlerbehebung
[ESP32-E22_OE3WAS_V2.0.3.pdf](https://github.com/user-attachments/files/17250256/ESP32-E22_OE3WAS_V2.0.3.pdf)
[esp32-e22_v2.0.3.zip](https://github.com/user-attachments/files/17250257/esp32-e22_v2.0.3.zip)

**Comment by karamo** [comment]
In der nächsten Version sind:
1) Footprint für Schraubklemme schon gefunden.
2) Beschriftung der Steckerleisten vollständig.

Offen ist nur noch die Frage, ob auf EN = RESET ein zusätzlicher Elko erforderlich wäre.
Taster ist nicht notwendig, da auf dem ESP32-Board.

**Comment by DK9BT** [comment]
merged to main
