### ISSUE TITLE
Gehäuse

### ISSUE THREAD

**Issue by DK9BT** [DK9BT/esp32-e22-lora-board#8]
Gehäusevorschläge:

https://www.amazon.de/dp/B08XNMZF2V

Vorteil: Ohne Schraubendreher zu öffnen....Transparent für Display -> universell

Platine: 132x80 mm passt genau rein mit 2  M5 Gewinden zur Befestigung

**Comment by DK9BT** [comment]
oder eines mit Schrauben:
https://www.amazon.de/dp/B0CZ6CYHLS

**Comment by karamo** [comment]
• Wasserdichte Anschlussdose, IP65 Elektrische Projektbox Verteilerdose Staubdicht Wetterfest, ABS Kabelgehäuse Verteilerkasten für Indoor Outdoor Elektronikkabel (Transparent 15,8 x 9 x 6,4 cm)
https://amzn.eu/d/4mfVIbA

• andere Gehäuse
Aussengehäuse http://www.schubert-gehaeuse.de/aussengehaeuse.html

Weissblechgehäuse http://www.schubert-gehaeuse.de/weissblechgehaeuse.html
